export const diseases = [
  {
    id: "common-cold",
    name: "Common Cold",
    tier: 1,
    definition: "A mild viral infection of the upper respiratory tract.",
    description:
      "Usually self-limited over several days. Symptoms are often focused on the nose and throat with mild fatigue.",
    treatment:
      "Supportive care: hydration, rest, throat soothing measures, and over-the-counter symptom relief as appropriate.",
    symptomIds: ["runny_nose", "sore_throat", "cough", "sneezing", "mild_fever", "fatigue"],
    tags: ["cough", "sore throat", "runny nose", "fatigue", "sneezing"],
    profile: {
      demographics: { agePeak: 28, ageSpread: 22, sexBias: { F: 1.0, M: 1.0 } },
      vitals: { temp: [37.0, 38.2], bpm: [80, 102], sys: [104, 126], dia: [66, 82] },
    },
  },
  {
    id: "influenza",
    name: "Influenza",
    tier: 1,
    definition: "An acute viral respiratory illness with systemic symptoms.",
    description:
      "Often starts abruptly and can cause high fever, myalgia, chills, and significant fatigue compared with a typical cold.",
    treatment:
      "Supportive care and, when clinically appropriate and early, antiviral therapy such as oseltamivir.",
    symptomIds: ["high_fever", "chills", "body_aches", "fatigue", "headache", "cough"],
    tags: ["fever", "body aches", "chills", "fatigue"],
    profile: {
      demographics: { agePeak: 34, ageSpread: 24, sexBias: { F: 1.0, M: 1.0 } },
      vitals: { temp: [38.3, 40.1], bpm: [92, 118], sys: [102, 132], dia: [64, 86] },
    },
  },
  {
    id: "norovirus",
    name: "Norovirus",
    tier: 1,
    definition: "A highly contagious viral gastroenteritis.",
    description:
      "Typically causes sudden onset nausea, vomiting, and diarrhea, sometimes with low-grade fever and abdominal cramps.",
    treatment:
      "Oral rehydration and electrolyte replacement; antiemetics may be considered for symptom control.",
    symptomIds: ["nausea", "vomiting", "diarrhea", "abdominal_cramps", "low_fever"],
    tags: ["nausea", "vomiting", "diarrhea", "stomach pain"],
    profile: {
      demographics: { agePeak: 30, ageSpread: 20, sexBias: { F: 1.0, M: 1.0 } },
      vitals: { temp: [37.2, 38.4], bpm: [92, 118], sys: [98, 122], dia: [62, 80] },
    },
  },
  {
    id: "strep-throat",
    name: "Strep Throat",
    tier: 2,
    definition: "A bacterial throat infection caused by group A streptococcus.",
    description:
      "Can cause sudden sore throat, painful swallowing, fever, and swollen neck lymph nodes, often without cough.",
    treatment:
      "Antibiotic therapy after confirmation plus analgesics and hydration for symptom relief.",
    symptomIds: ["sore_throat", "painful_swallowing", "high_fever", "swollen_lymph_nodes", "headache"],
    tags: ["sore throat", "fever", "swallowing pain", "lymph nodes"],
    profile: {
      demographics: { agePeak: 19, ageSpread: 10, sexBias: { F: 1.0, M: 1.0 } },
      vitals: { temp: [38.0, 39.6], bpm: [90, 112], sys: [100, 126], dia: [64, 82] },
    },
  },
  {
    id: "migraine",
    name: "Migraine",
    tier: 2,
    definition: "A recurrent neurologic headache disorder, often one-sided and disabling.",
    description:
      "Episodes can include throbbing head pain, nausea, and sensitivity to light or sound, sometimes with visual aura.",
    treatment:
      "Acute migraine therapy (for example NSAIDs or triptans when appropriate), hydration, and trigger management.",
    symptomIds: ["unilateral_headache", "photophobia", "nausea", "aura", "fatigue"],
    tags: ["headache", "light sensitivity", "nausea", "aura"],
    profile: {
      demographics: { agePeak: 32, ageSpread: 13, sexBias: { F: 1.2, M: 0.9 } },
      vitals: { temp: [36.4, 37.4], bpm: [72, 98], sys: [104, 132], dia: [66, 86] },
    },
  },
  {
    id: "food-poisoning",
    name: "Food Poisoning",
    tier: 2,
    definition: "An acute gastrointestinal illness from contaminated food or drink.",
    description:
      "Usually presents with nausea, vomiting, diarrhea, abdominal cramps, and occasionally fever after a suspicious meal.",
    treatment:
      "Hydration-first supportive care; targeted antimicrobial therapy only when specific pathogen or severe risk warrants.",
    symptomIds: ["nausea", "vomiting", "diarrhea", "abdominal_cramps", "low_fever", "fatigue"],
    tags: ["nausea", "vomiting", "diarrhea", "meal exposure"],
    profile: {
      demographics: { agePeak: 34, ageSpread: 20, sexBias: { F: 1.0, M: 1.0 } },
      vitals: { temp: [37.0, 38.6], bpm: [88, 112], sys: [100, 126], dia: [62, 82] },
    },
  },
  {
    id: "uti",
    name: "Urinary Tract Infection",
    tier: 2,
    definition: "A bacterial infection affecting part of the urinary system.",
    description:
      "Commonly causes burning urination, urinary frequency, pelvic discomfort, and sometimes low fever.",
    treatment:
      "Appropriate antibiotic therapy guided by presentation and local resistance patterns, plus hydration.",
    symptomIds: ["dysuria", "urinary_frequency", "pelvic_pain", "low_fever", "fatigue"],
    tags: ["burning urination", "urinary frequency", "pelvic pain"],
    profile: {
      demographics: { agePeak: 36, ageSpread: 18, sexBias: { F: 1.35, M: 0.75 } },
      vitals: { temp: [37.0, 38.3], bpm: [82, 106], sys: [102, 132], dia: [64, 86] },
    },
  },
  {
    id: "mononucleosis",
    name: "Mononucleosis",
    tier: 2,
    definition: "A viral illness, often caused by Epstein-Barr virus, that can produce prolonged fatigue.",
    description:
      "Common findings include severe fatigue, sore throat, fever, swollen lymph nodes, and sometimes enlarged spleen.",
    treatment:
      "Supportive care with rest, hydration, and analgesics; avoid contact sports if splenic enlargement is suspected.",
    symptomIds: ["fatigue", "sore_throat", "high_fever", "swollen_lymph_nodes", "headache"],
    tags: ["mono", "fatigue", "sore throat", "lymph nodes", "fever"],
    profile: {
      demographics: { agePeak: 21, ageSpread: 9, sexBias: { F: 1.0, M: 1.0 } },
      vitals: { temp: [37.8, 39.0], bpm: [86, 108], sys: [100, 126], dia: [64, 84] },
    },
  },
  {
    id: "meningitis",
    name: "Meningitis",
    tier: 3,
    definition: "Inflammation of the protective membranes around the brain and spinal cord.",
    description:
      "Can present with severe headache, fever, neck stiffness, light sensitivity, confusion, and urgent neurologic risk.",
    treatment:
      "Emergency evaluation with urgent empiric therapy and supportive care based on suspected etiology.",
    symptomIds: ["high_fever", "headache", "neck_stiffness", "photophobia", "confusion"],
    tags: ["headache", "neck stiffness", "fever", "confusion", "light sensitivity"],
    profile: {
      demographics: { agePeak: 29, ageSpread: 16, sexBias: { F: 1.0, M: 1.0 } },
      vitals: { temp: [38.5, 40.2], bpm: [96, 124], sys: [104, 144], dia: [66, 92] },
    },
  },
  {
    id: "appendicitis",
    name: "Appendicitis",
    tier: 3,
    definition: "Acute inflammation of the appendix, often requiring urgent surgery.",
    description:
      "Pain commonly starts near the navel and shifts to the right lower abdomen, often with nausea, appetite loss, and fever.",
    treatment:
      "Urgent surgical evaluation, often appendectomy, with perioperative antibiotics when indicated.",
    symptomIds: ["right_lower_quadrant_pain", "abdominal_cramps", "nausea", "low_fever", "rebound_tenderness"],
    tags: ["abdominal pain", "right lower quadrant", "nausea", "appendix"],
    profile: {
      demographics: { agePeak: 24, ageSpread: 12, sexBias: { F: 0.95, M: 1.05 } },
      vitals: { temp: [37.7, 39.0], bpm: [96, 124], sys: [106, 136], dia: [66, 88] },
    },
  },
  {
    id: "myocardial-infarction",
    name: "Heart Attack (Myocardial Infarction)",
    tier: 3,
    definition: "Damage to heart muscle due to reduced blood flow in coronary arteries.",
    description:
      "Typical symptoms include chest pressure, shortness of breath, sweating, and pain spreading to arm, jaw, or back.",
    treatment:
      "Emergency reperfusion pathway plus antiplatelet/antithrombotic and cardiology-directed acute management.",
    symptomIds: ["chest_pressure", "dyspnea", "diaphoresis", "arm_jaw_pain", "nausea"],
    tags: ["chest pain", "heart attack", "jaw pain", "shortness of breath"],
    profile: {
      demographics: { agePeak: 63, ageSpread: 10, sexBias: { F: 0.85, M: 1.2 } },
      vitals: { temp: [36.3, 37.4], bpm: [92, 126], sys: [124, 176], dia: [74, 104] },
    },
  },
  {
    id: "stroke",
    name: "Stroke",
    tier: 3,
    definition: "Sudden interruption of blood flow to part of the brain causing neurologic deficits.",
    description:
      "Symptoms may include facial droop, one-sided weakness, speech difficulty, confusion, and abrupt onset.",
    treatment:
      "Immediate stroke protocol with urgent imaging and time-sensitive reperfusion eligibility assessment.",
    symptomIds: ["facial_droop", "unilateral_weakness", "slurred_speech", "confusion", "headache"],
    tags: ["FAST", "weakness", "speech trouble", "facial droop", "stroke"],
    profile: {
      demographics: { agePeak: 67, ageSpread: 11, sexBias: { F: 0.9, M: 1.1 } },
      vitals: { temp: [36.2, 37.5], bpm: [84, 116], sys: [136, 192], dia: [80, 110] },
    },
  },
  {
    id: "celiac-disease",
    name: "Celiac Disease",
    tier: 2,
    definition: "An immune-mediated disorder triggered by gluten that damages the small intestine.",
    description:
      "Can involve bloating, chronic diarrhea, abdominal discomfort, weight loss, and nutrient deficiency symptoms.",
    treatment:
      "Strict lifelong gluten-free diet with nutritional monitoring and correction of deficiencies.",
    symptomIds: ["bloating", "persistent_diarrhea", "abdominal_cramps", "weight_loss", "fatigue"],
    tags: ["gluten", "bloating", "diarrhea", "weight loss", "celiac"],
    profile: {
      demographics: { agePeak: 33, ageSpread: 16, sexBias: { F: 1.2, M: 0.9 } },
      vitals: { temp: [36.3, 37.4], bpm: [74, 98], sys: [102, 130], dia: [64, 86] },
    },
  },
  {
    id: "crohns-disease",
    name: "Crohn's Disease",
    tier: 2,
    definition: "A chronic inflammatory bowel disease affecting the gastrointestinal tract.",
    description:
      "Frequently causes abdominal pain, persistent diarrhea, fatigue, weight loss, and may include blood in stool.",
    treatment:
      "Anti-inflammatory and immunomodulating therapy tailored to severity, with nutrition and flare management.",
    symptomIds: ["abdominal_cramps", "persistent_diarrhea", "fatigue", "weight_loss", "blood_in_stool"],
    tags: ["ibd", "crohn", "abdominal pain", "diarrhea", "blood in stool"],
    profile: {
      demographics: { agePeak: 30, ageSpread: 13, sexBias: { F: 1.0, M: 1.0 } },
      vitals: { temp: [36.8, 38.0], bpm: [78, 104], sys: [100, 130], dia: [64, 86] },
    },
  },
  {
    id: "pneumonia",
    name: "Pneumonia",
    tier: 2,
    definition: "An infection that inflames the air sacs in one or both lungs.",
    description:
      "May cause fever, productive cough, chest discomfort with breathing, shortness of breath, and fatigue.",
    treatment:
      "Severity-based antimicrobial therapy when bacterial etiology is likely, plus supportive respiratory care.",
    symptomIds: ["high_fever", "cough_with_phlegm", "pleuritic_chest_pain", "dyspnea", "fatigue"],
    tags: ["lung infection", "productive cough", "fever", "shortness of breath"],
    profile: {
      demographics: { agePeak: 52, ageSpread: 22, sexBias: { F: 1.0, M: 1.0 } },
      vitals: { temp: [38.0, 40.0], bpm: [92, 122], sys: [104, 140], dia: [66, 90] },
    },
  },
  {
    id: "pancreatitis",
    name: "Pancreatitis",
    tier: 3,
    definition: "Inflammation of the pancreas that can cause severe upper abdominal pain.",
    description:
      "Commonly presents with intense upper abdominal pain radiating to the back, nausea, vomiting, and elevated heart rate.",
    treatment:
      "Hospital-based supportive management with IV fluids, pain control, bowel rest, and treatment of underlying cause.",
    symptomIds: ["epigastric_pain", "back_radiation_pain", "nausea", "vomiting", "tachycardia"],
    tags: ["upper abdominal pain", "pancreas", "back pain", "nausea", "vomiting"],
    profile: {
      demographics: { agePeak: 48, ageSpread: 16, sexBias: { F: 0.95, M: 1.05 } },
      vitals: { temp: [37.4, 39.1], bpm: [98, 128], sys: [104, 142], dia: [66, 92] },
    },
  },
  {
    id: "overactive-bladder",
    name: "Overactive Bladder",
    tier: 2,
    definition: "A syndrome of urinary urgency, often with frequency and nocturia, without infection.",
    description:
      "Symptoms include sudden urge to urinate, frequent voiding, and waking at night to urinate, sometimes with urge leakage.",
    treatment:
      "Bladder training, fluid/caffeine timing changes, pelvic floor therapy, and medication when indicated.",
    symptomIds: ["urinary_urgency", "urinary_frequency", "nocturia", "urge_incontinence"],
    tags: ["urgency", "frequent urination", "night urination", "bladder"],
    profile: {
      demographics: { agePeak: 56, ageSpread: 18, sexBias: { F: 1.25, M: 0.85 } },
      vitals: { temp: [36.4, 37.5], bpm: [72, 102], sys: [104, 140], dia: [66, 90] },
    },
  },
  {
    id: "heartburn",
    name: "Heartburn (GERD-like reflux)",
    tier: 1,
    definition: "A burning chest sensation from reflux of stomach contents into the esophagus.",
    description:
      "Often worse after meals or when lying down, with sour taste or regurgitation and relief from antacid therapy.",
    treatment:
      "Lifestyle adjustments and acid suppression therapy such as antacids, H2 blockers, or PPIs as appropriate.",
    symptomIds: ["retrosternal_burning", "acid_regurgitation", "postprandial_worse", "worse_lying_flat"],
    tags: ["reflux", "heartburn", "burning chest", "acid taste"],
    profile: {
      demographics: { agePeak: 42, ageSpread: 18, sexBias: { F: 1.0, M: 1.0 } },
      vitals: { temp: [36.4, 37.4], bpm: [68, 98], sys: [104, 138], dia: [66, 90] },
    },
  },
];

export const symptomLabels = {
  cough: "Persistent cough",
  sore_throat: "Sore throat",
  runny_nose: "Runny nose",
  sneezing: "Frequent sneezing",
  mild_fever: "Mild fever",
  low_fever: "Low fever",
  high_fever: "High fever",
  fatigue: "Fatigue",
  body_aches: "Body aches",
  headache: "Headache",
  chills: "Chills",
  nausea: "Nausea",
  vomiting: "Vomiting",
  diarrhea: "Diarrhea",
  abdominal_cramps: "Abdominal cramps",
  painful_swallowing: "Painful swallowing",
  swollen_lymph_nodes: "Swollen neck lymph nodes",
  unilateral_headache: "One-sided throbbing headache",
  photophobia: "Light sensitivity",
  aura: "Visual aura",
  dysuria: "Burning urination",
  urinary_frequency: "Frequent urge to urinate",
  pelvic_pain: "Lower pelvic pain",
  neck_stiffness: "Neck stiffness",
  confusion: "Confusion",
  right_lower_quadrant_pain: "Right lower abdominal pain",
  rebound_tenderness: "Pain worse when pressure is released",
  chest_pressure: "Chest pressure or heaviness",
  dyspnea: "Shortness of breath",
  diaphoresis: "Profuse sweating",
  arm_jaw_pain: "Pain radiating to arm or jaw",
  facial_droop: "Facial droop",
  unilateral_weakness: "One-sided weakness",
  slurred_speech: "Slurred or difficult speech",
  bloating: "Bloating",
  persistent_diarrhea: "Persistent diarrhea",
  weight_loss: "Unintentional weight loss",
  blood_in_stool: "Blood in stool",
  cough_with_phlegm: "Cough with phlegm",
  pleuritic_chest_pain: "Chest pain when breathing deeply",
  epigastric_pain: "Upper central abdominal pain",
  back_radiation_pain: "Pain radiating to the back",
  tachycardia: "Fast heart rate",
  urinary_urgency: "Sudden urgent need to urinate",
  nocturia: "Waking at night to urinate",
  urge_incontinence: "Leakage with sudden urge",
  retrosternal_burning: "Burning behind the breastbone",
  acid_regurgitation: "Sour acid coming up into throat/mouth",
  postprandial_worse: "Worse after meals",
  worse_lying_flat: "Worse when lying flat",
};

export const patientNamePool = {
  first: [
    "Jordan",
    "Mateo",
    "Taylor",
    "Avery",
    "Riley",
    "Sage",
    "Imani",
    "Noah",
    "Priya",
    "Kai",
    "Elena",
    "Malik",
    "Harper",
    "Micah",
    "Ari",
    "Zoe",
    "Luca",
    "Mina",
  ],
  last: [
    "Ellis",
    "Rivera",
    "Morgan",
    "Kim",
    "Patel",
    "Nguyen",
    "Brooks",
    "Santos",
    "Campbell",
    "Ali",
    "Lopez",
    "Foster",
    "Hughes",
    "Diaz",
    "Carter",
    "Wright",
  ],
};

export const identityPool = ["Woman", "Man", "Nonbinary", "Trans woman", "Trans man"];

export const redHerringChoices = [
  {
    id: "red-herring-weather",
    text: "Did recent weather changes start all of this?",
    reveal: [],
    anxietyDelta: 5,
    painDelta: 0,
    responses: [
      "I do not think weather is the main issue.",
      "Maybe, but that does not explain how bad I feel.",
    ],
    repeatResponses: ["I already said I do not think weather is it.", "Same answer, I doubt weather caused this."],
  },
  {
    id: "red-herring-travel",
    text: "Have you recently flown on a plane this month?",
    reveal: [],
    anxietyDelta: 4,
    painDelta: 0,
    responses: ["No recent flights.", "I have not traveled by plane lately."],
    repeatResponses: ["Still no recent flights.", "Nope, same answer."],
  },
  {
    id: "red-herring-zodiac",
    text: "Do your symptoms get worse based on your zodiac cycle?",
    reveal: [],
    anxietyDelta: 9,
    painDelta: 1,
    responses: ["I do not think that has anything to do with it.", "That feels unrelated to why I am here."],
    repeatResponses: ["I already said that seems unrelated.", "Please ask medical questions."],
  },
  {
    id: "red-herring-energy-drink",
    text: "Would an energy drink fix this quickly for you?",
    reveal: [],
    anxietyDelta: 8,
    painDelta: 1,
    responses: ["No, that would not fix this.", "I do not think an energy drink helps this problem."],
    repeatResponses: ["Still no, that is not the issue.", "I already answered that."],
  },
  {
    id: "red-herring-screen-time",
    text: "Could too much phone screen time be the whole cause?",
    reveal: [],
    anxietyDelta: 6,
    painDelta: 0,
    responses: ["I doubt it is just that.", "Maybe not helping, but this feels bigger than that."],
    repeatResponses: ["Same answer, seems unlikely.", "I already answered that question."],
  },
  {
    id: "red-herring-caffeine-cutoff",
    text: "How many coffees did you have this morning exactly?",
    reveal: [],
    anxietyDelta: 4,
    painDelta: 0,
    responses: ["Just one, but this feels unrelated.", "Not enough to explain all this."],
    repeatResponses: ["Same coffee amount as I said.", "I already answered that."],
  },
  {
    id: "red-herring-office-chair",
    text: "Did your office chair setup trigger this whole thing?",
    reveal: [],
    anxietyDelta: 5,
    painDelta: 0,
    responses: ["I do not think my chair explains these symptoms.", "Maybe posture matters, but this feels different."],
    repeatResponses: ["Still do not think that is it.", "I already said that seems unlikely."],
  },
  {
    id: "red-herring-laundry-detergent",
    text: "Did you switch laundry detergent this week?",
    reveal: [],
    anxietyDelta: 5,
    painDelta: 0,
    responses: ["No recent change there.", "I did not change detergents."],
    repeatResponses: ["Still no detergent change.", "No, same answer as before."],
  },
  {
    id: "red-herring-sleep-app",
    text: "What did your sleep tracker app score last night?",
    reveal: [],
    anxietyDelta: 6,
    painDelta: 0,
    responses: ["I am not focused on app scores right now.", "Not sure, but this feels more serious."],
    repeatResponses: ["I still do not think that is the key issue.", "I already answered this."],
  },
  {
    id: "red-herring-step-count",
    text: "Could low step count this week explain everything?",
    reveal: [],
    anxietyDelta: 5,
    painDelta: 0,
    responses: ["I doubt steps explain all of this.", "Maybe activity is down, but this is beyond that."],
    repeatResponses: ["Same answer, seems unlikely.", "Still do not think that is the cause."],
  },
];

export const ambiguousReplies = [
  "Maybe, I guess.",
  "Kind of, sometimes.",
  "Possibly, yeah.",
  "It's possible.",
  "I think so.",
  "I can't remember.",
  "I guess so, on and off.",
  "Not really, I do not think so.",
  "Could be, maybe.",
  "Sort of, but not always.",
  "I am leaning yes, but not strongly.",
  "More like no than yes.",
  "Hard to pin down, honestly.",
  "A little bit, I think.",
  "Sometimes that happens, yeah.",
  "Not that I have noticed much.",
  "It does happen occasionally.",
  "I would not say that exactly.",
  "Probably, at least a little.",
  "Maybe not, hard to say.",
  "I think so, but I am unsure.",
  "Only now and then.",
  "Could go either way.",
  "Yeah, somewhat.",
  "No, not really.",
  "I guess that fits a little.",
  "I am not fully sure, but maybe.",
  "Sometimes yes, sometimes no.",
  "More yes than no, I think.",
  "I would not rule it out.",
  "I am not confident either way.",
];

export const complaintPools = {
  upper_respiratory: [
    "I feel run down and my throat hurts.",
    "My nose and throat have been bothering me all day.",
    "I cannot shake this cough and scratchy throat.",
    "I have been sneezing and feeling off for a couple of days.",
  ],
  viral_systemic: [
    "I have chills and feel terrible all over.",
    "I feel feverish and my whole body aches.",
    "I got hit with this fast and now everything hurts.",
    "I am exhausted and achy from head to toe.",
  ],
  gastro_acute: [
    "I cannot stop throwing up.",
    "My stomach is in knots and I keep running to the bathroom.",
    "I have had sudden nausea and diarrhea since last night.",
    "I feel sick to my stomach and cannot keep things down.",
  ],
  throat_severe: [
    "My throat hurts so much I do not want to swallow.",
    "Swallowing even water hurts right now.",
    "My throat pain got bad really quickly.",
    "It feels like my throat is raw and on fire.",
  ],
  headache_neuro: [
    "I have a pounding headache and light hurts.",
    "My head is throbbing and bright lights make it worse.",
    "This headache is intense and I feel queasy.",
    "I can barely function because this headache will not let up.",
  ],
  urinary_irritative: [
    "It burns when I pee and I keep needing to go.",
    "I keep rushing to the bathroom and it stings.",
    "I feel pressure low down and nonstop urinary urgency.",
    "I am peeing a lot and it is uncomfortable each time.",
  ],
  fatigue_throat: [
    "I am wiped out and my throat is on fire.",
    "I feel unusually exhausted and my throat is really sore.",
    "I keep sleeping but still feel drained and sick.",
    "My energy is gone and my throat pain is getting worse.",
  ],
  abdominal_acute: [
    "My stomach pain moved and now it is sharp on the lower right side.",
    "My belly pain started central and now sits low on one side.",
    "This abdominal pain has gotten sharper over the day.",
    "My lower right abdomen hurts more every hour.",
  ],
  respiratory_lower: [
    "I cannot stop coughing and breathing feels heavy.",
    "I am coughing up mucus and feel short of breath.",
    "Taking deep breaths hurts and I keep coughing.",
    "I have fever with a chesty cough and low energy.",
  ],
  gi_chronic: [
    "My gut has been acting up for weeks and I keep losing weight.",
    "I keep having bowel trouble and feel worn out all the time.",
    "My stomach has been bad for weeks, not just a day.",
    "I have ongoing cramps and my weight keeps dropping.",
  ],
  chest_pressure: [
    "It feels like an elephant is sitting on my chest.",
    "I have heavy chest pressure that will not let up.",
    "My chest feels tight and something is very wrong.",
    "I feel crushing pressure in my chest and I am scared.",
  ],
  neuro_focal: [
    "My face feels weird and my words are coming out wrong.",
    "One side feels off and I am having trouble speaking.",
    "My speech got slurred all of a sudden.",
    "My arm feels weak and my face does not feel normal.",
  ],
};

export const starterCases = [
  {
    id: "case-cold",
    patient: {
      age: 24,
      heightCm: 165,
      weightKg: 60,
      complaint: "I feel run down and my throat hurts.",
      bp: "112/74",
      bpm: 94,
      temperatureC: 37.8,
    },
    diagnosisId: "common-cold",
    complaintCategories: ["upper_respiratory", "viral_systemic"],
    startingAnxiety: 20,
    startingPain: 18,
    interviewChoices: [
      {
        id: "onset",
        text: "When did this start, and did it come on suddenly?",
        reveal: ["fatigue"],
        anxietyDelta: -2,
        painDelta: 0,
        responses: [
          "It started about two days ago and kind of crept up on me.",
          "I noticed it yesterday morning, then it slowly got worse.",
        ],
        repeatResponses: ["Still the same timeline, about two days.", "I already shared when it started."],
      },
      {
        id: "throat-breathing",
        text: "Are you having cough, sore throat, or breathing trouble?",
        reveal: ["cough", "sore_throat"],
        anxietyDelta: -1,
        painDelta: 1,
        responses: [
          "Sore throat and cough, yes. Breathing is okay.",
          "My throat hurts and I keep coughing, but I am not short of breath.",
        ],
        repeatResponses: ["No breathing trouble, still just throat and cough.", "Same answer, cough and sore throat."],
      },
      {
        id: "nasal-followup",
        text: "Any runny nose or sneezing?",
        reveal: ["runny_nose", "sneezing"],
        anxietyDelta: 0,
        painDelta: 0,
        requiresAny: ["sore_throat", "cough"],
        responses: ["Yeah, both. I keep sneezing and my nose is running.", "My nose has been running all day and I am sneezing a lot."],
        repeatResponses: ["Still runny nose and sneezing.", "No change, same nasal symptoms."],
      },
      {
        id: "fever",
        text: "Have you had a fever, and how high did it get?",
        reveal: ["mild_fever"],
        anxietyDelta: 0,
        painDelta: 0,
        responses: ["Low fever only, nothing very high.", "I felt warm, but it has been mild."],
        repeatResponses: ["Still mild, not high.", "No change on fever, still low-grade."],
      },
      {
        id: "dismissive",
        text: "This sounds minor. Are you sure you needed to come in?",
        reveal: [],
        anxietyDelta: 9,
        painDelta: 1,
        responses: ["I came because I feel bad and wanted advice.", "That makes me feel dismissed, honestly."],
        repeatResponses: ["You already said that. I still need help.", "Please stop minimizing this."],
      },
    ],
  },
  {
    id: "case-flu",
    patient: {
      age: 31,
      heightCm: 178,
      weightKg: 79,
      complaint: "I have chills and feel terrible all over.",
      bp: "118/76",
      bpm: 102,
      temperatureC: 39.1,
    },
    diagnosisId: "influenza",
    complaintCategories: ["viral_systemic", "upper_respiratory"],
    startingAnxiety: 26,
    startingPain: 25,
    interviewChoices: [
      {
        id: "fever-chills",
        text: "What has your fever and chills been like today?",
        reveal: ["high_fever", "chills"],
        anxietyDelta: -1,
        painDelta: 1,
        responses: ["Chills started last night and my fever got high.", "I was shaking with chills and still feel hot."],
        repeatResponses: ["Still high fever and chills.", "No change, same fever and chills."],
      },
      {
        id: "body-pain",
        text: "Where are the aches worst right now?",
        reveal: ["body_aches", "fatigue", "headache"],
        anxietyDelta: -1,
        painDelta: 0,
        responses: ["Everywhere, especially my back and head.", "Whole body aches, plus a pounding headache."],
        repeatResponses: ["Still all-over aches.", "Same severe body pain."],
      },
      {
        id: "respiratory",
        text: "Any cough, chest pain, or shortness of breath?",
        reveal: ["cough"],
        anxietyDelta: 0,
        painDelta: 0,
        requiresAny: ["high_fever", "body_aches"],
        responses: ["Dry cough yes, no chest pain.", "I am coughing but breathing is okay."],
        repeatResponses: ["Still just cough, no chest pain.", "Same respiratory symptoms."],
      },
      {
        id: "gi",
        text: "Any nausea, vomiting, or diarrhea?",
        reveal: [],
        anxietyDelta: 3,
        painDelta: 0,
        responses: ["Not really, mostly fever and aches.", "No major stomach symptoms."],
        repeatResponses: ["Still no major GI symptoms.", "Same as before, no GI issues."],
      },
      {
        id: "accusatory",
        text: "Are you sure this is not exaggerated?",
        reveal: [],
        anxietyDelta: 12,
        painDelta: 1,
        responses: ["No, this is real. I feel awful.", "I am not exaggerating. I need help."],
        repeatResponses: ["I already answered that.", "That question is frustrating."],
      },
    ],
  },
  {
    id: "case-noro",
    patient: {
      age: 19,
      heightCm: 170,
      weightKg: 66,
      complaint: "I cannot stop throwing up.",
      bp: "104/70",
      bpm: 108,
      temperatureC: 37.9,
    },
    diagnosisId: "norovirus",
    complaintCategories: ["gastro_acute"],
    startingAnxiety: 30,
    startingPain: 32,
    interviewChoices: [
      {
        id: "vomit-frequency",
        text: "How often are you vomiting and having diarrhea?",
        reveal: ["nausea", "vomiting", "diarrhea", "abdominal_cramps"],
        anxietyDelta: -2,
        painDelta: 1,
        responses: ["Several times today. It keeps happening.", "Pretty frequent, with painful stomach cramps."],
        repeatResponses: ["Still frequent.", "No improvement yet."],
      },
      {
        id: "hydration",
        text: "Have you been able to keep fluids down?",
        reveal: ["low_fever", "fatigue"],
        anxietyDelta: -1,
        painDelta: 0,
        requiresAny: ["vomiting"],
        responses: ["Barely, just tiny sips.", "Not much. I feel dry and weak."],
        repeatResponses: ["Still hard to keep fluids down.", "No change, still dehydrated."],
      },
      {
        id: "meal-timing",
        text: "Did this begin after any specific meal or event?",
        reveal: ["nausea"],
        anxietyDelta: 0,
        painDelta: 0,
        responses: ["Started a few hours after a shared meal.", "It began after dinner out with friends."],
        repeatResponses: ["Same timing, after that meal.", "I already shared the meal timing."],
      },
      {
        id: "resp-focus",
        text: "Any cough or sore throat with this?",
        reveal: [],
        anxietyDelta: 4,
        painDelta: 0,
        responses: ["No, this is all stomach related.", "No respiratory symptoms."],
        repeatResponses: ["Still no cough or sore throat.", "Same answer, no respiratory symptoms."],
      },
      {
        id: "judgment",
        text: "Did you maybe cause this with bad food choices?",
        reveal: [],
        anxietyDelta: 10,
        painDelta: 1,
        responses: ["That is not helpful right now.", "Please just help me feel better."],
        repeatResponses: ["You already asked that.", "That question is making me more anxious."],
      },
    ],
  },
  {
    id: "case-strep",
    patient: {
      age: 16,
      heightCm: 162,
      weightKg: 54,
      complaint: "My throat hurts so much I do not want to swallow.",
      bp: "110/72",
      bpm: 99,
      temperatureC: 38.7,
    },
    diagnosisId: "strep-throat",
    complaintCategories: ["throat_severe"],
    startingAnxiety: 24,
    startingPain: 28,
    interviewChoices: [
      {
        id: "swallow",
        text: "Is swallowing painful, even with water?",
        reveal: ["sore_throat", "painful_swallowing"],
        anxietyDelta: -1,
        painDelta: 1,
        responses: ["Yeah, even water hurts.", "Swallowing is really painful."],
        repeatResponses: ["Still painful to swallow.", "No change, swallowing still hurts."],
      },
      {
        id: "fever",
        text: "Have you had fever or chills?",
        reveal: ["high_fever"],
        anxietyDelta: 0,
        painDelta: 0,
        responses: ["Yes, fever since last night.", "Fever has been pretty high."],
        repeatResponses: ["Still feverish.", "No change on fever."],
      },
      {
        id: "lymph",
        text: "Do your neck glands feel swollen or tender?",
        reveal: ["swollen_lymph_nodes", "headache"],
        anxietyDelta: -1,
        painDelta: 0,
        requiresAny: ["sore_throat"],
        responses: ["Yes, my neck feels sore and swollen.", "My neck glands hurt when I touch them."],
        repeatResponses: ["Still swollen.", "Same neck tenderness."],
      },
      {
        id: "cough-check",
        text: "Are you also coughing a lot?",
        reveal: [],
        anxietyDelta: 2,
        painDelta: 0,
        responses: ["Not really, coughing is not the issue.", "No major cough."],
        repeatResponses: ["Still no significant cough.", "Same answer, little to no cough."],
      },
      {
        id: "dismissive",
        text: "Maybe this is just irritation and not infection.",
        reveal: [],
        anxietyDelta: 9,
        painDelta: 1,
        responses: ["It feels worse than simple irritation.", "I am worried because it hurts so much."],
        repeatResponses: ["Please take this seriously.", "That is not reassuring."],
      },
    ],
  },
  {
    id: "case-migraine",
    patient: {
      age: 28,
      heightCm: 172,
      weightKg: 68,
      complaint: "I have a pounding headache and light hurts.",
      bp: "116/75",
      bpm: 88,
      temperatureC: 36.9,
    },
    diagnosisId: "migraine",
    complaintCategories: ["headache_neuro"],
    startingAnxiety: 22,
    startingPain: 36,
    interviewChoices: [
      {
        id: "pain-side",
        text: "Is the headache mostly on one side and throbbing?",
        reveal: ["unilateral_headache"],
        anxietyDelta: -1,
        painDelta: 1,
        responses: ["Yes, mostly one side and throbbing.", "It is one-sided and pulsating."],
        repeatResponses: ["Still one-sided.", "Same throbbing one-sided pain."],
      },
      {
        id: "light-sound",
        text: "Are light or noise making it worse?",
        reveal: ["photophobia"],
        anxietyDelta: -1,
        painDelta: 0,
        responses: ["Light definitely makes it worse.", "Yes, bright lights are awful right now."],
        repeatResponses: ["Still very light-sensitive.", "No change, light still hurts."],
      },
      {
        id: "aura",
        text: "Did you have visual changes before the headache?",
        reveal: ["aura"],
        anxietyDelta: 0,
        painDelta: 0,
        requiresAny: ["unilateral_headache"],
        responses: ["Yes, I saw flashing zig-zag patterns first.", "I had blurry shimmering vision before it started."],
        repeatResponses: ["Same aura pattern as before.", "I already mentioned the visual aura."],
      },
      {
        id: "nausea",
        text: "Do you feel nauseated with this headache?",
        reveal: ["nausea", "fatigue"],
        anxietyDelta: 0,
        painDelta: 0,
        responses: ["Yes, nauseated and wiped out.", "I feel sick to my stomach with it."],
        repeatResponses: ["Still nauseated.", "No change, still nauseous."],
      },
      {
        id: "judgment",
        text: "Could this just be stress and not a real migraine?",
        reveal: [],
        anxietyDelta: 10,
        painDelta: 1,
        responses: ["Stress maybe, but this feels like a migraine attack.", "That sounds dismissive. This is severe."],
        repeatResponses: ["You already asked that.", "Please do not dismiss my pain."],
      },
    ],
  },
  {
    id: "case-uti",
    patient: {
      age: 33,
      heightCm: 168,
      weightKg: 64,
      complaint: "It burns when I pee and I keep needing to go.",
      bp: "114/73",
      bpm: 96,
      temperatureC: 37.7,
    },
    diagnosisId: "uti",
    complaintCategories: ["urinary_irritative"],
    startingAnxiety: 24,
    startingPain: 22,
    interviewChoices: [
      {
        id: "urination",
        text: "Is there burning urination and frequent urge?",
        reveal: ["dysuria", "urinary_frequency"],
        anxietyDelta: -1,
        painDelta: 0,
        responses: ["Yes, both. It burns and I keep going.", "Exactly, burning and urgency all day."],
        repeatResponses: ["Still burning and frequent.", "No change, same urinary symptoms."],
      },
      {
        id: "pelvic",
        text: "Any lower pelvic pain or pressure?",
        reveal: ["pelvic_pain"],
        anxietyDelta: -1,
        painDelta: 1,
        requiresAny: ["dysuria"],
        responses: ["Yes, a dull pressure low in my pelvis.", "There is definitely lower abdominal pressure."],
        repeatResponses: ["Still that same pressure.", "No change in pelvic discomfort."],
      },
      {
        id: "fever",
        text: "Have you noticed fever or fatigue?",
        reveal: ["low_fever", "fatigue"],
        anxietyDelta: 0,
        painDelta: 0,
        responses: ["A little feverish and tired.", "Mild fever and fatigue, yes."],
        repeatResponses: ["Still mildly feverish.", "Same mild fever and fatigue."],
      },
      {
        id: "respiratory",
        text: "Any cough, congestion, or sore throat too?",
        reveal: [],
        anxietyDelta: 3,
        painDelta: 0,
        responses: ["No, this is urinary only.", "No respiratory symptoms."],
        repeatResponses: ["Still no respiratory symptoms.", "Same answer, no cough or sore throat."],
      },
      {
        id: "dismissive",
        text: "This might just be irritation. Are you overreacting?",
        reveal: [],
        anxietyDelta: 11,
        painDelta: 1,
        responses: ["I do not think so. It hurts and is constant.", "I am not overreacting, this is painful."],
        repeatResponses: ["Please stop saying that.", "You already asked that and it is upsetting."],
      },
    ],
  },
  {
    id: "case-mono",
    patient: {
      age: 20,
      heightCm: 174,
      weightKg: 71,
      complaint: "I am wiped out and my throat is on fire.",
      bp: "108/70",
      bpm: 98,
      temperatureC: 38.2,
    },
    diagnosisId: "mononucleosis",
    complaintCategories: ["fatigue_throat", "throat_severe"],
    startingAnxiety: 25,
    startingPain: 24,
    interviewChoices: [
      {
        id: "fatigue-duration",
        text: "How long have you felt this level of exhaustion?",
        reveal: ["fatigue"],
        anxietyDelta: -1,
        painDelta: 0,
        responses: ["Over a week. I sleep and still feel drained.", "It has been days and my energy never comes back."],
        repeatResponses: ["Still exhausted, same as before.", "I already said the fatigue has lasted days."],
      },
      {
        id: "throat-fever",
        text: "Any severe sore throat and fever with this?",
        reveal: ["sore_throat", "high_fever"],
        anxietyDelta: -1,
        painDelta: 1,
        responses: ["Yes, sore throat and fever together.", "My throat is really sore and I have had fevers."],
        repeatResponses: ["Still sore throat plus fever.", "No change, same throat and fever symptoms."],
      },
      {
        id: "nodes",
        text: "Do your neck glands feel swollen or tender?",
        reveal: ["swollen_lymph_nodes", "headache"],
        anxietyDelta: -1,
        painDelta: 0,
        requiresAny: ["sore_throat"],
        responses: ["Yeah, the lumps in my neck are tender.", "My neck glands are puffy and sore."],
        repeatResponses: ["Still swollen and tender.", "Same neck gland swelling."],
      },
      {
        id: "quick-fix",
        text: "Can you just push through this with caffeine?",
        reveal: [],
        anxietyDelta: 8,
        painDelta: 1,
        responses: ["I have tried. It is not that kind of tired.", "That does not seem to help at all."],
        repeatResponses: ["Please stop minimizing this.", "I already said this is not normal tiredness."],
      },
    ],
  },
  {
    id: "case-appendix",
    patient: {
      age: 22,
      heightCm: 176,
      weightKg: 74,
      complaint: "My stomach pain moved and now it is sharp on the lower right side.",
      bp: "122/78",
      bpm: 110,
      temperatureC: 38.1,
    },
    diagnosisId: "appendicitis",
    complaintCategories: ["abdominal_acute", "gastro_acute"],
    startingAnxiety: 28,
    startingPain: 41,
    interviewChoices: [
      {
        id: "pain-location",
        text: "Where exactly is the pain now, and did it move there?",
        reveal: ["right_lower_quadrant_pain", "abdominal_cramps"],
        anxietyDelta: -1,
        painDelta: 2,
        responses: ["It started near my belly button then moved lower right.", "Now it is mostly in the lower right and sharper."],
        repeatResponses: ["Still lower right and sharp.", "Same location, still right lower side."],
      },
      {
        id: "release-tenderness",
        text: "Does it hurt more when pressure is released?",
        reveal: ["rebound_tenderness"],
        anxietyDelta: 0,
        painDelta: 1,
        requiresAny: ["right_lower_quadrant_pain"],
        responses: ["Yes, that release hurts a lot.", "Pressing is bad, releasing is worse."],
        repeatResponses: ["Still true, release hurts more.", "No change, rebound pain is still there."],
      },
      {
        id: "nausea-fever",
        text: "Any nausea or fever since this started?",
        reveal: ["nausea", "low_fever"],
        anxietyDelta: -1,
        painDelta: 0,
        responses: ["Yes, queasy and a low fever.", "I feel sick and warm."],
        repeatResponses: ["Still nauseated.", "Same nausea and low fever."],
      },
      {
        id: "delay-care",
        text: "Want to wait it out another day first?",
        reveal: [],
        anxietyDelta: 12,
        painDelta: 2,
        responses: ["I do not think I can wait, it is getting worse.", "I am worried this is serious."],
        repeatResponses: ["Please do not tell me to wait.", "You already asked and I am still worried."],
      },
    ],
  },
  {
    id: "case-pneumonia",
    patient: {
      age: 47,
      heightCm: 169,
      weightKg: 82,
      complaint: "I cannot stop coughing and breathing feels heavy.",
      bp: "128/80",
      bpm: 106,
      temperatureC: 38.6,
    },
    diagnosisId: "pneumonia",
    complaintCategories: ["respiratory_lower", "viral_systemic"],
    startingAnxiety: 27,
    startingPain: 29,
    interviewChoices: [
      {
        id: "cough-type",
        text: "Is your cough dry, or are you bringing up mucus?",
        reveal: ["cough_with_phlegm"],
        anxietyDelta: -1,
        painDelta: 0,
        responses: ["There is phlegm, not just a dry cough.", "Yeah, I am coughing stuff up."],
        repeatResponses: ["Still productive cough.", "Same cough with phlegm."],
      },
      {
        id: "breath-chest",
        text: "Any chest pain when taking a deep breath?",
        reveal: ["pleuritic_chest_pain", "dyspnea"],
        anxietyDelta: -1,
        painDelta: 1,
        requiresAny: ["cough_with_phlegm"],
        responses: ["Yes, sharp when I breathe in.", "Deep breaths hurt and I feel short of breath."],
        repeatResponses: ["Still painful with deep breathing.", "Same chest pain on breathing."],
      },
      {
        id: "fever-energy",
        text: "Have you had fever and low energy too?",
        reveal: ["high_fever", "fatigue"],
        anxietyDelta: 0,
        painDelta: 0,
        responses: ["Yes to both, fever and fatigue.", "I have had fever and I feel drained."],
        repeatResponses: ["Still feverish and tired.", "No change on fever/fatigue."],
      },
      {
        id: "ignore-lungs",
        text: "Could this just be allergies and not infection?",
        reveal: [],
        anxietyDelta: 10,
        painDelta: 1,
        responses: ["It feels much worse than allergies.", "I do not think this is just allergies."],
        repeatResponses: ["Please stop downplaying it.", "I already said this feels worse than allergies."],
      },
    ],
  },
  {
    id: "case-crohns",
    patient: {
      age: 29,
      heightCm: 171,
      weightKg: 58,
      complaint: "My gut has been acting up for weeks and I keep losing weight.",
      bp: "109/71",
      bpm: 92,
      temperatureC: 37.4,
    },
    diagnosisId: "crohns-disease",
    complaintCategories: ["gi_chronic"],
    startingAnxiety: 29,
    startingPain: 26,
    interviewChoices: [
      {
        id: "timeline-weeks",
        text: "How long have the bowel issues been going on?",
        reveal: ["persistent_diarrhea", "fatigue"],
        anxietyDelta: -1,
        painDelta: 0,
        responses: ["Weeks, maybe over a month now.", "It has been ongoing, not just a day or two."],
        repeatResponses: ["Still chronic, not acute.", "Same timeline, several weeks."],
      },
      {
        id: "pain-pattern",
        text: "Do you also get cramping abdominal pain?",
        reveal: ["abdominal_cramps"],
        anxietyDelta: -1,
        painDelta: 1,
        responses: ["Yes, cramping comes in waves.", "I get repeated crampy pain."],
        repeatResponses: ["Still cramping.", "No change in cramp pattern."],
      },
      {
        id: "stool-change",
        text: "Any blood in stool or weight changes?",
        reveal: ["blood_in_stool", "weight_loss"],
        anxietyDelta: 0,
        painDelta: 0,
        requiresAny: ["persistent_diarrhea"],
        responses: ["I have seen blood sometimes, and lost weight.", "Yes, less weight and occasional blood."],
        repeatResponses: ["Still true, blood at times and weight loss.", "No change there."],
      },
      {
        id: "blame-diet",
        text: "Could this just be from one bad meal?",
        reveal: [],
        anxietyDelta: 9,
        painDelta: 1,
        responses: ["It has lasted too long for one meal.", "This has been going on for weeks."],
        repeatResponses: ["I already explained it is chronic.", "Please listen, this is not a one-day issue."],
      },
    ],
  },
  {
    id: "case-heart-attack",
    patient: {
      age: 58,
      heightCm: 177,
      weightKg: 86,
      complaint: "It feels like an elephant is sitting on my chest.",
      bp: "146/90",
      bpm: 114,
      temperatureC: 37.1,
    },
    diagnosisId: "myocardial-infarction",
    complaintCategories: ["chest_pressure"],
    startingAnxiety: 36,
    startingPain: 48,
    interviewChoices: [
      {
        id: "chest-pressure",
        text: "Can you describe the chest discomfort in your own words?",
        reveal: ["chest_pressure"],
        anxietyDelta: -1,
        painDelta: 2,
        responses: ["Heavy pressure, not a sharp poke.", "It is crushing and constant."],
        repeatResponses: ["Still heavy pressure.", "No change, still crushing."],
      },
      {
        id: "radiation",
        text: "Does the pain travel to your arm, jaw, neck, or back?",
        reveal: ["arm_jaw_pain"],
        anxietyDelta: -1,
        painDelta: 1,
        requiresAny: ["chest_pressure"],
        responses: ["Yes, up into my jaw and left arm.", "My left arm and jaw hurt too."],
        repeatResponses: ["Still radiating to arm/jaw.", "Same spread pattern as before."],
      },
      {
        id: "breathing-sweat",
        text: "Any sweating, nausea, or breathlessness with this?",
        reveal: ["dyspnea", "diaphoresis", "nausea"],
        anxietyDelta: 0,
        painDelta: 1,
        responses: ["I am sweaty, a bit nauseated, and short of breath.", "Yes to all three, especially sweating."],
        repeatResponses: ["Still sweaty and short of breath.", "Same symptoms continue."],
      },
      {
        id: "minimize-cardiac",
        text: "Could this just be indigestion and anxiety?",
        reveal: [],
        anxietyDelta: 13,
        painDelta: 2,
        responses: ["This feels way worse than heartburn.", "I am scared this is my heart."],
        repeatResponses: ["Please stop saying that.", "I already said this feels serious."],
      },
    ],
  },
  {
    id: "case-stroke",
    patient: {
      age: 67,
      heightCm: 173,
      weightKg: 79,
      complaint: "My face feels weird and my words are coming out wrong.",
      bp: "168/96",
      bpm: 101,
      temperatureC: 36.8,
    },
    diagnosisId: "stroke",
    complaintCategories: ["neuro_focal", "headache_neuro"],
    startingAnxiety: 38,
    startingPain: 20,
    interviewChoices: [
      {
        id: "fast-face",
        text: "Can you smile for me? Any drooping on one side?",
        reveal: ["facial_droop"],
        anxietyDelta: -1,
        painDelta: 0,
        responses: ["One side does not move right.", "My left side feels slack."],
        repeatResponses: ["Still drooping.", "No improvement in the facial droop."],
      },
      {
        id: "fast-arm",
        text: "Can you lift both arms? Is one weaker?",
        reveal: ["unilateral_weakness"],
        anxietyDelta: -1,
        painDelta: 0,
        requiresAny: ["facial_droop"],
        responses: ["My right arm keeps drifting down.", "One arm is definitely weaker."],
        repeatResponses: ["Still weak on one side.", "No change in arm weakness."],
      },
      {
        id: "fast-speech",
        text: "Are you having trouble speaking clearly or finding words?",
        reveal: ["slurred_speech", "confusion"],
        anxietyDelta: 0,
        painDelta: 0,
        responses: ["Yes, words are slurred and mixed up.", "I know what I want to say but cannot say it right."],
        repeatResponses: ["Still slurred and confused.", "Same speech trouble."],
      },
      {
        id: "delay-neuro",
        text: "Should we just observe for a few hours first?",
        reveal: [],
        anxietyDelta: 14,
        painDelta: 1,
        responses: ["No, this started suddenly and feels urgent.", "Please do not wait. Something is wrong."],
        repeatResponses: ["I am getting more scared.", "Please act now."],
      },
    ],
  },
];
