import type { StarterCase } from "../types";
export const starterCases: StarterCase[] = [
  {
    id: "case-cold",
    patient: {
      age: 24,
      heightCm: 165,
      weightKg: 60,
      complaint: "I feel run down and my throat hurts.",
      bp: "112/74",
      bpm: 94,
      temperatureC: 37.8,
    },
    diagnosisId: "common-cold",
    complaintCategories: ["upper_respiratory", "viral_systemic"],
    caseTier: 0,
    startingAnxiety: 20,
    startingPain: 18,
    interviewChoices: [
      {
        id: "onset",
        text: "When did this start, and did it come on suddenly?",
        reveal: ["fatigue"],
        anxietyDelta: -2,
        painDelta: 0,
        responses: [
          "It started about two days ago and kind of crept up on me.",
          "I noticed it yesterday morning, then it slowly got worse.",
        ],
        repeatResponses: ["Still the same timeline, about two days.", "I already shared when it started."],
      },
      {
        id: "throat-breathing",
        text: "Are you having cough, sore throat, or breathing trouble?",
        reveal: ["cough", "sore_throat"],
        anxietyDelta: -1,
        painDelta: 1,
        responses: [
          "Sore throat and cough, yes. Breathing is okay.",
          "My throat hurts and I keep coughing, but I am not short of breath.",
        ],
        repeatResponses: ["No breathing trouble, still just throat and cough.", "Same answer, cough and sore throat."],
      },
      {
        id: "nasal-followup",
        text: "Any runny nose or sneezing?",
        reveal: ["runny_nose", "sneezing"],
        anxietyDelta: 0,
        painDelta: 0,
        requiresAny: ["sore_throat", "cough"],
        responses: ["Yeah, both. I keep sneezing and my nose is running.", "My nose has been running all day and I am sneezing a lot."],
        repeatResponses: ["Still runny nose and sneezing.", "No change, same nasal symptoms."],
      },
      {
        id: "fever",
        text: "Have you had a fever, and how high did it get?",
        reveal: ["mild_fever"],
        anxietyDelta: 0,
        painDelta: 0,
        responses: ["Low fever only, nothing very high.", "I felt warm, but it has been mild."],
        repeatResponses: ["Still mild, not high.", "No change on fever, still low-grade."],
      },
      {
        id: "dismissive",
        text: "This sounds minor. Are you sure you needed to come in?",
        reveal: [],
        anxietyDelta: 9,
        painDelta: 1,
        responses: ["I came because I feel bad and wanted advice.", "That makes me feel dismissed, honestly."],
        repeatResponses: ["You already said that. I still need help.", "Please stop minimizing this."],
      },
    ],
  },
  {
    id: "case-flu",
    patient: {
      age: 31,
      heightCm: 178,
      weightKg: 79,
      complaint: "I have chills and feel terrible all over.",
      bp: "118/76",
      bpm: 102,
      temperatureC: 39.1,
    },
    diagnosisId: "influenza",
    complaintCategories: ["viral_systemic", "upper_respiratory"],
    caseTier: 1,
    startingAnxiety: 26,
    startingPain: 25,
    interviewChoices: [
      {
        id: "fever-chills",
        text: "What has your fever and chills been like today?",
        reveal: ["high_fever", "chills"],
        anxietyDelta: -1,
        painDelta: 1,
        responses: ["Chills started last night and my fever got high.", "I was shaking with chills and still feel hot."],
        repeatResponses: ["Still high fever and chills.", "No change, same fever and chills."],
      },
      {
        id: "body-pain",
        text: "Where are the aches worst right now?",
        reveal: ["body_aches", "fatigue", "headache"],
        anxietyDelta: -1,
        painDelta: 0,
        responses: ["Everywhere, especially my back and head.", "Whole body aches, plus a pounding headache."],
        repeatResponses: ["Still all-over aches.", "Same severe body pain."],
      },
      {
        id: "respiratory",
        text: "Any cough, chest pain, or shortness of breath?",
        reveal: ["cough"],
        anxietyDelta: 0,
        painDelta: 0,
        requiresAny: ["high_fever", "body_aches"],
        responses: ["Dry cough yes, no chest pain.", "I am coughing but breathing is okay."],
        repeatResponses: ["Still just cough, no chest pain.", "Same respiratory symptoms."],
      },
      {
        id: "gi",
        text: "Any nausea, vomiting, or diarrhea?",
        reveal: [],
        anxietyDelta: 3,
        painDelta: 0,
        responses: ["Not really, mostly fever and aches.", "No major stomach symptoms."],
        repeatResponses: ["Still no major GI symptoms.", "Same as before, no GI issues."],
      },
      {
        id: "accusatory",
        text: "Are you sure this is not exaggerated?",
        reveal: [],
        anxietyDelta: 12,
        painDelta: 1,
        responses: ["No, this is real. I feel awful.", "I am not exaggerating. I need help."],
        repeatResponses: ["I already answered that.", "That question is frustrating."],
      },
    ],
  },
  {
    id: "case-noro",
    patient: {
      age: 19,
      heightCm: 170,
      weightKg: 66,
      complaint: "I cannot stop throwing up.",
      bp: "104/70",
      bpm: 108,
      temperatureC: 37.9,
    },
    diagnosisId: "norovirus",
    complaintCategories: ["gastro_acute"],
    caseTier: 0,
    startingAnxiety: 30,
    startingPain: 32,
    interviewChoices: [
      {
        id: "vomit-frequency",
        text: "How often are you vomiting and having diarrhea?",
        reveal: ["nausea", "vomiting", "diarrhea", "abdominal_cramps"],
        anxietyDelta: -2,
        painDelta: 1,
        responses: ["Several times today. It keeps happening.", "Pretty frequent, with painful stomach cramps."],
        repeatResponses: ["Still frequent.", "No improvement yet."],
      },
      {
        id: "hydration",
        text: "Have you been able to keep fluids down?",
        reveal: ["low_fever", "fatigue"],
        anxietyDelta: -1,
        painDelta: 0,
        requiresAny: ["vomiting"],
        responses: ["Barely, just tiny sips.", "Not much. I feel dry and weak."],
        repeatResponses: ["Still hard to keep fluids down.", "No change, still dehydrated."],
      },
      {
        id: "meal-timing",
        text: "Did this begin after any specific meal or event?",
        reveal: ["nausea"],
        anxietyDelta: 0,
        painDelta: 0,
        responses: ["Started a few hours after a shared meal.", "It began after dinner out with friends."],
        repeatResponses: ["Same timing, after that meal.", "I already shared the meal timing."],
      },
      {
        id: "resp-focus",
        text: "Any cough or sore throat with this?",
        reveal: [],
        anxietyDelta: 4,
        painDelta: 0,
        responses: ["No, this is all stomach related.", "No respiratory symptoms."],
        repeatResponses: ["Still no cough or sore throat.", "Same answer, no respiratory symptoms."],
      },
      {
        id: "judgment",
        text: "Did you maybe cause this with bad food choices?",
        reveal: [],
        anxietyDelta: 10,
        painDelta: 1,
        responses: ["That is not helpful right now.", "Please just help me feel better."],
        repeatResponses: ["You already asked that.", "That question is making me more anxious."],
      },
    ],
  },
  {
    id: "case-strep",
    patient: {
      age: 16,
      heightCm: 162,
      weightKg: 54,
      complaint: "My throat hurts so much I do not want to swallow.",
      bp: "110/72",
      bpm: 99,
      temperatureC: 38.7,
    },
    diagnosisId: "strep-throat",
    complaintCategories: ["throat_severe"],
    caseTier: 1,
    startingAnxiety: 24,
    startingPain: 28,
    interviewChoices: [
      {
        id: "swallow",
        text: "Is swallowing painful, even with water?",
        reveal: ["sore_throat", "painful_swallowing"],
        anxietyDelta: -1,
        painDelta: 1,
        responses: ["Yeah, even water hurts.", "Swallowing is really painful."],
        repeatResponses: ["Still painful to swallow.", "No change, swallowing still hurts."],
      },
      {
        id: "fever",
        text: "Have you had fever or chills?",
        reveal: ["high_fever"],
        anxietyDelta: 0,
        painDelta: 0,
        responses: ["Yes, fever since last night.", "Fever has been pretty high."],
        repeatResponses: ["Still feverish.", "No change on fever."],
      },
      {
        id: "lymph",
        text: "Do your neck glands feel swollen or tender?",
        reveal: ["swollen_lymph_nodes", "headache"],
        anxietyDelta: -1,
        painDelta: 0,
        requiresAny: ["sore_throat"],
        responses: ["Yes, my neck feels sore and swollen.", "My neck glands hurt when I touch them."],
        repeatResponses: ["Still swollen.", "Same neck tenderness."],
      },
      {
        id: "cough-check",
        text: "Are you also coughing a lot?",
        reveal: [],
        anxietyDelta: 2,
        painDelta: 0,
        responses: ["Not really, coughing is not the issue.", "No major cough."],
        repeatResponses: ["Still no significant cough.", "Same answer, little to no cough."],
      },
      {
        id: "dismissive",
        text: "Maybe this is just irritation and not infection.",
        reveal: [],
        anxietyDelta: 9,
        painDelta: 1,
        responses: ["It feels worse than simple irritation.", "I am worried because it hurts so much."],
        repeatResponses: ["Please take this seriously.", "That is not reassuring."],
      },
    ],
  },
  {
    id: "case-migraine",
    patient: {
      age: 28,
      heightCm: 172,
      weightKg: 68,
      complaint: "I have a pounding headache and light hurts.",
      bp: "116/75",
      bpm: 88,
      temperatureC: 36.9,
    },
    diagnosisId: "migraine",
    complaintCategories: ["headache_neuro"],
    caseTier: 1,
    startingAnxiety: 22,
    startingPain: 36,
    interviewChoices: [
      {
        id: "pain-side",
        text: "Is the headache mostly on one side and throbbing?",
        reveal: ["unilateral_headache"],
        anxietyDelta: -1,
        painDelta: 1,
        responses: ["Yes, mostly one side and throbbing.", "It is one-sided and pulsating."],
        repeatResponses: ["Still one-sided.", "Same throbbing one-sided pain."],
      },
      {
        id: "light-sound",
        text: "Are light or noise making it worse?",
        reveal: ["photophobia"],
        anxietyDelta: -1,
        painDelta: 0,
        responses: ["Light definitely makes it worse.", "Yes, bright lights are awful right now."],
        repeatResponses: ["Still very light-sensitive.", "No change, light still hurts."],
      },
      {
        id: "aura",
        text: "Did you have visual changes before the headache?",
        reveal: ["aura"],
        anxietyDelta: 0,
        painDelta: 0,
        requiresAny: ["unilateral_headache"],
        responses: ["Yes, I saw flashing zig-zag patterns first.", "I had blurry shimmering vision before it started."],
        repeatResponses: ["Same aura pattern as before.", "I already mentioned the visual aura."],
      },
      {
        id: "nausea",
        text: "Do you feel nauseated with this headache?",
        reveal: ["nausea", "fatigue"],
        anxietyDelta: 0,
        painDelta: 0,
        responses: ["Yes, nauseated and wiped out.", "I feel sick to my stomach with it."],
        repeatResponses: ["Still nauseated.", "No change, still nauseous."],
      },
      {
        id: "judgment",
        text: "Could this just be stress and not a real migraine?",
        reveal: [],
        anxietyDelta: 10,
        painDelta: 1,
        responses: ["Stress maybe, but this feels like a migraine attack.", "That sounds dismissive. This is severe."],
        repeatResponses: ["You already asked that.", "Please do not dismiss my pain."],
      },
    ],
  },
  {
    id: "case-uti",
    patient: {
      age: 33,
      heightCm: 168,
      weightKg: 64,
      complaint: "It burns when I pee and I keep needing to go.",
      bp: "114/73",
      bpm: 96,
      temperatureC: 37.7,
    },
    diagnosisId: "uti",
    complaintCategories: ["urinary_irritative"],
    caseTier: 0,
    startingAnxiety: 24,
    startingPain: 22,
    interviewChoices: [
      {
        id: "urination",
        text: "Is there burning urination and frequent urge?",
        reveal: ["dysuria", "urinary_frequency"],
        anxietyDelta: -1,
        painDelta: 0,
        responses: ["Yes, both. It burns and I keep going.", "Exactly, burning and urgency all day."],
        repeatResponses: ["Still burning and frequent.", "No change, same urinary symptoms."],
      },
      {
        id: "pelvic",
        text: "Any lower pelvic pain or pressure?",
        reveal: ["pelvic_pain"],
        anxietyDelta: -1,
        painDelta: 1,
        requiresAny: ["dysuria"],
        responses: ["Yes, a dull pressure low in my pelvis.", "There is definitely lower abdominal pressure."],
        repeatResponses: ["Still that same pressure.", "No change in pelvic discomfort."],
      },
      {
        id: "fever",
        text: "Have you noticed fever or fatigue?",
        reveal: ["low_fever", "fatigue"],
        anxietyDelta: 0,
        painDelta: 0,
        responses: ["A little feverish and tired.", "Mild fever and fatigue, yes."],
        repeatResponses: ["Still mildly feverish.", "Same mild fever and fatigue."],
      },
      {
        id: "respiratory",
        text: "Any cough, congestion, or sore throat too?",
        reveal: [],
        anxietyDelta: 3,
        painDelta: 0,
        responses: ["No, this is urinary only.", "No respiratory symptoms."],
        repeatResponses: ["Still no respiratory symptoms.", "Same answer, no cough or sore throat."],
      },
      {
        id: "dismissive",
        text: "This might just be irritation. Are you overreacting?",
        reveal: [],
        anxietyDelta: 11,
        painDelta: 1,
        responses: ["I do not think so. It hurts and is constant.", "I am not overreacting, this is painful."],
        repeatResponses: ["Please stop saying that.", "You already asked that and it is upsetting."],
      },
    ],
  },
  {
    id: "case-mono",
    patient: {
      age: 20,
      heightCm: 174,
      weightKg: 71,
      complaint: "I am wiped out and my throat is on fire.",
      bp: "108/70",
      bpm: 98,
      temperatureC: 38.2,
    },
    diagnosisId: "mononucleosis",
    complaintCategories: ["fatigue_throat", "throat_severe"],
    caseTier: 1,
    startingAnxiety: 25,
    startingPain: 24,
    interviewChoices: [
      {
        id: "fatigue-duration",
        text: "How long have you felt this level of exhaustion?",
        reveal: ["fatigue"],
        anxietyDelta: -1,
        painDelta: 0,
        responses: ["Over a week. I sleep and still feel drained.", "It has been days and my energy never comes back."],
        repeatResponses: ["Still exhausted, same as before.", "I already said the fatigue has lasted days."],
      },
      {
        id: "throat-fever",
        text: "Any severe sore throat and fever with this?",
        reveal: ["sore_throat", "high_fever"],
        anxietyDelta: -1,
        painDelta: 1,
        responses: ["Yes, sore throat and fever together.", "My throat is really sore and I have had fevers."],
        repeatResponses: ["Still sore throat plus fever.", "No change, same throat and fever symptoms."],
      },
      {
        id: "nodes",
        text: "Do your neck glands feel swollen or tender?",
        reveal: ["swollen_lymph_nodes", "headache"],
        anxietyDelta: -1,
        painDelta: 0,
        requiresAny: ["sore_throat"],
        responses: ["Yeah, the lumps in my neck are tender.", "My neck glands are puffy and sore."],
        repeatResponses: ["Still swollen and tender.", "Same neck gland swelling."],
      },
      {
        id: "quick-fix",
        text: "Can you just push through this with caffeine?",
        reveal: [],
        anxietyDelta: 8,
        painDelta: 1,
        responses: ["I have tried. It is not that kind of tired.", "That does not seem to help at all."],
        repeatResponses: ["Please stop minimizing this.", "I already said this is not normal tiredness."],
      },
    ],
  },
  {
    id: "case-appendix",
    patient: {
      age: 22,
      heightCm: 176,
      weightKg: 74,
      complaint: "My stomach pain moved and now it is sharp on the lower right side.",
      bp: "122/78",
      bpm: 110,
      temperatureC: 38.1,
    },
    diagnosisId: "appendicitis",
    complaintCategories: ["abdominal_acute", "gastro_acute"],
    caseTier: 2,
    startingAnxiety: 28,
    startingPain: 41,
    interviewChoices: [
      {
        id: "pain-location",
        text: "Where exactly is the pain now, and did it move there?",
        reveal: ["right_lower_quadrant_pain", "abdominal_cramps"],
        anxietyDelta: -1,
        painDelta: 2,
        responses: ["It started near my belly button then moved lower right.", "Now it is mostly in the lower right and sharper."],
        repeatResponses: ["Still lower right and sharp.", "Same location, still right lower side."],
      },
      {
        id: "release-tenderness",
        text: "Does it hurt more when pressure is released?",
        reveal: ["rebound_tenderness"],
        anxietyDelta: 0,
        painDelta: 1,
        requiresAny: ["right_lower_quadrant_pain"],
        responses: ["Yes, that release hurts a lot.", "Pressing is bad, releasing is worse."],
        repeatResponses: ["Still true, release hurts more.", "No change, rebound pain is still there."],
      },
      {
        id: "nausea-fever",
        text: "Any nausea or fever since this started?",
        reveal: ["nausea", "low_fever"],
        anxietyDelta: -1,
        painDelta: 0,
        responses: ["Yes, queasy and a low fever.", "I feel sick and warm."],
        repeatResponses: ["Still nauseated.", "Same nausea and low fever."],
      },
      {
        id: "delay-care",
        text: "Want to wait it out another day first?",
        reveal: [],
        anxietyDelta: 12,
        painDelta: 2,
        responses: ["I do not think I can wait, it is getting worse.", "I am worried this is serious."],
        repeatResponses: ["Please do not tell me to wait.", "You already asked and I am still worried."],
      },
    ],
  },
  {
    id: "case-pneumonia",
    patient: {
      age: 47,
      heightCm: 169,
      weightKg: 82,
      complaint: "I cannot stop coughing and breathing feels heavy.",
      bp: "128/80",
      bpm: 106,
      temperatureC: 38.6,
    },
    diagnosisId: "pneumonia",
    complaintCategories: ["respiratory_lower", "viral_systemic"],    caseTier: 2,    startingAnxiety: 27,
    startingPain: 29,
    interviewChoices: [
      {
        id: "cough-type",
        text: "Is your cough dry, or are you bringing up mucus?",
        reveal: ["cough_with_phlegm"],
        anxietyDelta: -1,
        painDelta: 0,
        responses: ["There is phlegm, not just a dry cough.", "Yeah, I am coughing stuff up."],
        repeatResponses: ["Still productive cough.", "Same cough with phlegm."],
      },
      {
        id: "breath-chest",
        text: "Any chest pain when taking a deep breath?",
        reveal: ["pleuritic_chest_pain", "dyspnea"],
        anxietyDelta: -1,
        painDelta: 1,
        requiresAny: ["cough_with_phlegm"],
        responses: ["Yes, sharp when I breathe in.", "Deep breaths hurt and I feel short of breath."],
        repeatResponses: ["Still painful with deep breathing.", "Same chest pain on breathing."],
      },
      {
        id: "fever-energy",
        text: "Have you had fever and low energy too?",
        reveal: ["high_fever", "fatigue"],
        anxietyDelta: 0,
        painDelta: 0,
        responses: ["Yes to both, fever and fatigue.", "I have had fever and I feel drained."],
        repeatResponses: ["Still feverish and tired.", "No change on fever/fatigue."],
      },
      {
        id: "ignore-lungs",
        text: "Could this just be allergies and not infection?",
        reveal: [],
        anxietyDelta: 10,
        painDelta: 1,
        responses: ["It feels much worse than allergies.", "I do not think this is just allergies."],
        repeatResponses: ["Please stop downplaying it.", "I already said this feels worse than allergies."],
      },
    ],
  },
  {
    id: "case-crohns",
    patient: {
      age: 29,
      heightCm: 171,
      weightKg: 58,
      complaint: "My gut has been acting up for weeks and I keep losing weight.",
      bp: "109/71",
      bpm: 92,
      temperatureC: 37.4,
    },
    diagnosisId: "crohns-disease",
    complaintCategories: ["gi_chronic"],
    caseTier: 2,
    startingAnxiety: 29,
    startingPain: 26,
    interviewChoices: [
      {
        id: "timeline-weeks",
        text: "How long have the bowel issues been going on?",
        reveal: ["persistent_diarrhea", "fatigue"],
        anxietyDelta: -1,
        painDelta: 0,
        responses: ["Weeks, maybe over a month now.", "It has been ongoing, not just a day or two."],
        repeatResponses: ["Still chronic, not acute.", "Same timeline, several weeks."],
      },
      {
        id: "pain-pattern",
        text: "Do you also get cramping abdominal pain?",
        reveal: ["abdominal_cramps"],
        anxietyDelta: -1,
        painDelta: 1,
        responses: ["Yes, cramping comes in waves.", "I get repeated crampy pain."],
        repeatResponses: ["Still cramping.", "No change in cramp pattern."],
      },
      {
        id: "stool-change",
        text: "Any blood in stool or weight changes?",
        reveal: ["blood_in_stool", "weight_loss"],
        anxietyDelta: 0,
        painDelta: 0,
        requiresAny: ["persistent_diarrhea"],
        responses: ["I have seen blood sometimes, and lost weight.", "Yes, less weight and occasional blood."],
        repeatResponses: ["Still true, blood at times and weight loss.", "No change there."],
      },
      {
        id: "blame-diet",
        text: "Could this just be from one bad meal?",
        reveal: [],
        anxietyDelta: 9,
        painDelta: 1,
        responses: ["It has lasted too long for one meal.", "This has been going on for weeks."],
        repeatResponses: ["I already explained it is chronic.", "Please listen, this is not a one-day issue."],
      },
    ],
  },
  {
    id: "case-heart-attack",
    patient: {
      age: 58,
      heightCm: 177,
      weightKg: 86,
      complaint: "It feels like an elephant is sitting on my chest.",
      bp: "146/90",
      bpm: 114,
      temperatureC: 37.1,
    },
    diagnosisId: "myocardial-infarction",
    complaintCategories: ["chest_pressure"],
    caseTier: 2,
    startingAnxiety: 36,
    startingPain: 48,
    interviewChoices: [
      {
        id: "chest-pressure",
        text: "Can you describe the chest discomfort in your own words?",
        reveal: ["chest_pressure"],
        anxietyDelta: -1,
        painDelta: 2,
        responses: ["Heavy pressure, not a sharp poke.", "It is crushing and constant."],
        repeatResponses: ["Still heavy pressure.", "No change, still crushing."],
      },
      {
        id: "radiation",
        text: "Does the pain travel to your arm, jaw, neck, or back?",
        reveal: ["arm_jaw_pain"],
        anxietyDelta: -1,
        painDelta: 1,
        requiresAny: ["chest_pressure"],
        responses: ["Yes, up into my jaw and left arm.", "My left arm and jaw hurt too."],
        repeatResponses: ["Still radiating to arm/jaw.", "Same spread pattern as before."],
      },
      {
        id: "breathing-sweat",
        text: "Any sweating, nausea, or breathlessness with this?",
        reveal: ["dyspnea", "diaphoresis", "nausea"],
        anxietyDelta: 0,
        painDelta: 1,
        responses: ["I am sweaty, a bit nauseated, and short of breath.", "Yes to all three, especially sweating."],
        repeatResponses: ["Still sweaty and short of breath.", "Same symptoms continue."],
      },
      {
        id: "minimize-cardiac",
        text: "Could this just be indigestion and anxiety?",
        reveal: [],
        anxietyDelta: 13,
        painDelta: 2,
        responses: ["This feels way worse than heartburn.", "I am scared this is my heart."],
        repeatResponses: ["Please stop saying that.", "I already said this feels serious."],
      },
    ],
  },
  {
    id: "case-stroke",
    patient: {
      age: 67,
      heightCm: 173,
      weightKg: 79,
      complaint: "My face feels weird and my words are coming out wrong.",
      bp: "168/96",
      bpm: 101,
      temperatureC: 36.8,
    },
    diagnosisId: "stroke",
    complaintCategories: ["neuro_focal", "headache_neuro"],
    startingAnxiety: 38,
    startingPain: 20,
    interviewChoices: [
      {
        id: "fast-face",
        text: "Can you smile for me? Any drooping on one side?",
        reveal: ["facial_droop"],
        anxietyDelta: -1,
        painDelta: 0,
        responses: ["One side does not move right.", "My left side feels slack."],
        repeatResponses: ["Still drooping.", "No improvement in the facial droop."],
      },
      {
        id: "fast-arm",
        text: "Can you lift both arms? Is one weaker?",
        reveal: ["unilateral_weakness"],
        anxietyDelta: -1,
        painDelta: 0,
        requiresAny: ["facial_droop"],
        responses: ["My right arm keeps drifting down.", "One arm is definitely weaker."],
        repeatResponses: ["Still weak on one side.", "No change in arm weakness."],
      },
      {
        id: "fast-speech",
        text: "Are you having trouble speaking clearly or finding words?",
        reveal: ["slurred_speech", "confusion"],
        anxietyDelta: 0,
        painDelta: 0,
        responses: ["Yes, words are slurred and mixed up.", "I know what I want to say but cannot say it right."],
        repeatResponses: ["Still slurred and confused.", "Same speech trouble."],
      },
      {
        id: "delay-neuro",
        text: "Would you like to just be observed for a few hours first?",
        reveal: [],
        anxietyDelta: 14,
        painDelta: 1,
        responses: ["No, this started suddenly and feels urgent.", "Please do not wait. Something is wrong."],
        repeatResponses: ["I am getting more scared.", "Please act now."],
      },
    ],
  },
];
