import type { StarterCase } from "../types";
export const patientNamePool: { first: string[]; last: string[] } = {
  first: [
    "Jordan",
    "Mateo",
    "Taylor",
    "Avery",
    "Riley",
    "Sage",
    "Imani",
    "Noah",
    "Priya",
    "Kai",
    "Elena",
    "Malik",
    "Harper",
    "Micah",
    "Ari",
    "Zoe",
    "Luca",
    "Mina",
  ],
  last: [
    "Ellis",
    "Rivera",
    "Morgan",
    "Kim",
    "Patel",
    "Nguyen",
    "Brooks",
    "Santos",
    "Campbell",
    "Ali",
    "Lopez",
    "Foster",
    "Hughes",
    "Diaz",
    "Carter",
    "Wright",
  ],
};

export const identityPool: string[] = ["Woman", "Man", "Nonbinary", "Trans woman", "Trans man"];

export const redHerringChoices: StarterCase["interviewChoices"] = [
  {
    id: "red-herring-weather",
    text: "Did recent weather changes start all of this?",
    reveal: [],
    anxietyDelta: 5,
    painDelta: 0,
    responses: [
      "I do not think weather is the main issue.",
      "Maybe, but that does not explain how bad I feel.",
    ],
    repeatResponses: ["I already said I do not think weather is it.", "Same answer, I doubt weather caused this."],
  },
  {
    id: "red-herring-travel",
    text: "Have you recently flown on a plane this month?",
    reveal: [],
    anxietyDelta: 4,
    painDelta: 0,
    responses: ["No recent flights.", "I have not traveled by plane lately."],
    repeatResponses: ["Still no recent flights.", "Nope, same answer."],
  },
  {
    id: "red-herring-zodiac",
    text: "Do your symptoms get worse based on your zodiac cycle?",
    reveal: [],
    anxietyDelta: 9,
    painDelta: 1,
    responses: ["I do not think that has anything to do with it.", "That feels unrelated to why I am here."],
    repeatResponses: ["I already said that seems unrelated.", "Please ask medical questions."],
  },
  {
    id: "red-herring-energy-drink",
    text: "Would an energy drink fix this quickly for you?",
    reveal: [],
    anxietyDelta: 8,
    painDelta: 1,
    responses: ["No, that would not fix this.", "I do not think an energy drink helps this problem."],
    repeatResponses: ["Still no, that is not the issue.", "I already answered that."],
  },
  {
    id: "red-herring-screen-time",
    text: "Could too much phone screen time be the whole cause?",
    reveal: [],
    anxietyDelta: 6,
    painDelta: 0,
    responses: ["I doubt it is just that.", "Maybe not helping, but this feels bigger than that."],
    repeatResponses: ["Same answer, seems unlikely.", "I already answered that question."],
  },
  {
    id: "red-herring-caffeine-cutoff",
    text: "How many coffees did you have this morning exactly?",
    reveal: [],
    anxietyDelta: 4,
    painDelta: 0,
    responses: ["Just one, but this feels unrelated.", "Not enough to explain all this."],
    repeatResponses: ["Same coffee amount as I said.", "I already answered that."],
  },
  {
    id: "red-herring-office-chair",
    text: "Did your office chair setup trigger this whole thing?",
    reveal: [],
    anxietyDelta: 5,
    painDelta: 0,
    responses: ["I do not think my chair explains these symptoms.", "Maybe posture matters, but this feels different."],
    repeatResponses: ["Still do not think that is it.", "I already said that seems unlikely."],
  },
  {
    id: "red-herring-laundry-detergent",
    text: "Did you switch laundry detergent this week?",
    reveal: [],
    anxietyDelta: 5,
    painDelta: 0,
    responses: ["No recent change there.", "I did not change detergents."],
    repeatResponses: ["Still no detergent change.", "No, same answer as before."],
  },
  {
    id: "red-herring-sleep-app",
    text: "What did your sleep tracker app score last night?",
    reveal: [],
    anxietyDelta: 6,
    painDelta: 0,
    responses: ["I am not focused on app scores right now.", "Not sure, but this feels more serious."],
    repeatResponses: ["I still do not think that is the key issue.", "I already answered this."],
  },
  {
    id: "red-herring-step-count",
    text: "Could low step count this week explain everything?",
    reveal: [],
    anxietyDelta: 5,
    painDelta: 0,
    responses: ["I doubt steps explain all of this.", "Maybe activity is down, but this is beyond that."],
    repeatResponses: ["Same answer, seems unlikely.", "Still do not think that is the cause."],
  },
];

export const ambiguousReplies: string[] = [
  "Maybe, I guess.",
  "Possibly, yeah.",
  "I think so.",
  "I can't remember.",
  "I guess so, on and off.",
  "Not really, I do not think so.",
  "Could be, maybe.",
  "Sort of, but not always.",
  "I am leaning yes, but not strongly.",
  "More like no than yes.",
  "Hard to say.",
  "A little bit, I think.",
  "Sometimes that happens, yeah.",
  "Not that I have noticed much.",
  "It does happen occasionally.",
  "I would not say that exactly.",
  "Probably, at least a little.",
  "Maybe not, hard to say.",
  "I think so, but I am unsure.",
  "Only now and then.",
  "If you think so.",
  "Yeah, somewhat.",
  "No, not really.",
  "I guess that fits a little.",
  "I am not fully sure, but maybe.",
  "Sometimes yes, sometimes no.",
  "More yes than no, I think.",
  "I would not rule it out.",
  "I am not confident either way.",
];

export const complaintPools: Record<string, string[]> = {
  upper_respiratory: [
    "I feel run down and my throat hurts.",
    "My nose and throat have been bothering me all day.",
    "I cannot shake this cough and scratchy throat.",
    "I have been sneezing and feeling off for a couple of days.",
  ],
  viral_systemic: [
    "I have chills and feel terrible all over.",
    "I feel feverish and my whole body aches.",
    "I got hit with this fast and now everything hurts.",
    "I am exhausted and achy from head to toe.",
  ],
  gastro_acute: [
    "I cannot stop throwing up.",
    "My stomach is in knots and I keep running to the bathroom.",
    "I have had sudden nausea and diarrhea since last night.",
    "I feel sick to my stomach and cannot keep things down.",
  ],
  throat_severe: [
    "My throat hurts so much I do not want to swallow.",
    "Swallowing even water hurts right now.",
    "My throat pain got bad really quickly.",
    "It feels like my throat is raw and on fire.",
  ],
  headache_neuro: [
    "I have a pounding headache and light hurts.",
    "My head is throbbing and bright lights make it worse.",
    "This headache is intense and I feel queasy.",
    "I can barely function because this headache will not let up.",
  ],
  urinary_irritative: [
    "It burns when I pee and I keep needing to go.",
    "I keep rushing to the bathroom and it stings.",
    "I feel pressure low down and nonstop urinary urgency.",
    "I am peeing a lot and it is uncomfortable each time.",
  ],
  fatigue_throat: [
    "I am wiped out and my throat is on fire.",
    "I feel unusually exhausted and my throat is really sore.",
    "I keep sleeping but still feel drained and sick.",
    "My energy is gone and my throat pain is getting worse.",
  ],
  abdominal_acute: [
    "My stomach pain moved and now it is sharp on the lower right side.",
    "My belly pain started central and now sits low on one side.",
    "This abdominal pain has gotten sharper over the day.",
    "My lower right abdomen hurts more every hour.",
  ],
  respiratory_lower: [
    "I cannot stop coughing and breathing feels heavy.",
    "I am coughing up mucus and feel short of breath.",
    "Taking deep breaths hurts and I keep coughing.",
    "I have fever with a chesty cough and low energy.",
  ],
  gi_chronic: [
    "My gut has been acting up for weeks and I keep losing weight.",
    "I keep having bowel trouble and feel worn out all the time.",
    "My stomach has been bad for weeks, not just a day.",
    "I have ongoing cramps and my weight keeps dropping.",
  ],
  chest_pressure: [
    "It feels like an elephant is sitting on my chest.",
    "I have heavy chest pressure that will not let up.",
    "My chest feels tight and something is very wrong.",
    "I feel crushing pressure in my chest and I am scared.",
  ],
  neuro_focal: [
    "My face feels weird and my words are coming out wrong.",
    "One side feels off and I am having trouble speaking.",
    "My speech got slurred all of a sudden.",
    "My arm feels weak and my face does not feel normal.",
  ],
};
